CREATE TABLE public.tcg_user_list
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    list_name       VARCHAR(75)                             NOT NULL,
    list_type       TCG_LIST_TYPE,
    list_visibility TCG_LIST_VISIBILITY,
    tcg_id          BIGINT                                  NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_tcg_user_list PRIMARY KEY (id)
);

ALTER TABLE public.tcg_user_list
    ADD CONSTRAINT FK_TCG_USER_LIST_ON_TCG FOREIGN KEY (tcg_id) REFERENCES public.tcg_list (id);

ALTER TABLE public.tcg_user_list
    ADD CONSTRAINT FK_TCG_USER_LIST_ON_USER FOREIGN KEY (user_id) REFERENCES public.app_users (id);