CREATE TABLE tcglist_entry
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    list_id  BIGINT                                  NOT NULL,
    card_id  BIGINT                                  NOT NULL,
    quantity INTEGER,
    CONSTRAINT pk_tcglistentry PRIMARY KEY (id)
);

ALTER TABLE tcglist_entry
    ADD CONSTRAINT FK_TCGLISTENTRY_ON_CARD FOREIGN KEY (card_id) REFERENCES card (id);

ALTER TABLE tcglist_entry
    ADD CONSTRAINT FK_TCGLISTENTRY_ON_LIST FOREIGN KEY (list_id) REFERENCES public.tcg_user_list (id);