CREATE TABLE public.app_users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(50)  NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE public.user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

ALTER TABLE public.app_users
    ADD CONSTRAINT uc_app_users_email UNIQUE (email);

ALTER TABLE public.app_users
    ADD CONSTRAINT uc_app_users_username UNIQUE (username);

ALTER TABLE public.user_roles
    ADD CONSTRAINT fk_userol_on_roles_entity FOREIGN KEY (role_id) REFERENCES public.roles (id);

ALTER TABLE public.user_roles
    ADD CONSTRAINT fk_userol_on_user_entity FOREIGN KEY (user_id) REFERENCES public.app_users (id);