CREATE TABLE public.user_sessions
(
    session_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token         TEXT         NOT NULL,
    refresh_token VARCHAR(255) NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked       BOOLEAN      NOT NULL,
    user_id       BIGINT,
    CONSTRAINT pk_user_sessions PRIMARY KEY (session_id)
);

ALTER TABLE public.user_sessions
    ADD CONSTRAINT FK_USER_SESSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES public.app_users (id);