CREATE TABLE public.tcg_list
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_tcg_list PRIMARY KEY (id)
);

ALTER TABLE public.tcg_list
    ADD CONSTRAINT uc_tcg_list_code UNIQUE (code);