CREATE TABLE card_rarity
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code   VARCHAR(255) NOT NULL,
    tcg_id BIGINT,
    name   VARCHAR(255),
    CONSTRAINT pk_card_rarity PRIMARY KEY (id)
);

ALTER TABLE card_rarity
    ADD CONSTRAINT uc_card_rarity_code UNIQUE (code);

ALTER TABLE card_rarity
    ADD CONSTRAINT FK_CARD_RARITY_ON_TCG FOREIGN KEY (tcg_id) REFERENCES public.tcg_list (id);