CREATE TABLE card
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    card_name           VARCHAR(255),
    card_secondary_name VARCHAR(255),
    external_id         VARCHAR(255),
    set_code            VARCHAR(255),
    imageurl            VARCHAR(255),
    release_date        date,
    tcg_id              BIGINT NOT NULL,
    rarity_id           BIGINT NOT NULL,
    CONSTRAINT pk_card PRIMARY KEY (id)
);

ALTER TABLE card
    ADD CONSTRAINT FK_CARD_ON_RARITY FOREIGN KEY (rarity_id) REFERENCES card_rarity (id);

ALTER TABLE card
    ADD CONSTRAINT FK_CARD_ON_TCG FOREIGN KEY (tcg_id) REFERENCES public.tcg_list (id);